#!/bin/sh
#ESTO PUEDES EDITAR
EMUDIR=/usr/local/etc/multics/ #Ruta de tu configuracion Multics
CARPETA=Multics-R100-IP-$(curl -s -4 ifconfig.me) #Edita el nombre de la carpeta si quieres que sea distinta
REMOTE=Mega 

#NO EDITAR NI TOCAR
BACKUPDIR=`date +%Y` #ES PARA QUE CREE CARPETA POR AÑO
DIR=$CARPETA/$BACKUPDIR/ #ES PARA QUE CREE CARPETA POR NOMBRE_DE_CARPETA/AÑO/
NOMBRE=/tmp/backups-`date +%d-%m-%Y`.tar.gz
tar -zcvf $NOMBRE $EMUDIR
/usr/bin/rclone copy --update --verbose --transfers 30 --checkers 8 --contimeout 60s --timeout 300s --retries 3 --low-level-retries 10 --stats 1s "$NOMBRE" "$REMOTE:$DIR"
rm $NOMBRE
